"""empty message

Revision ID: e3f2c0ab2113
Revises: 5a1d5629563a
Create Date: 2023-05-31 12:37:02.612109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f2c0ab2113'
down_revision = '5a1d5629563a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
